## This notebook runs a simulation of a rope using ANCF elements to model the flexibility and the DCA to form and solve the equations of motion

In [1]:
import math
import pickle 
import numpy as np
import scipy as sp
import sympy as sym
import matplotlib.pyplot as plt
import MBstructs as MB
import MultiBodyFuncts as MBF
import dca_recursive

from numpy.linalg import inv
from scipy.integrate import odeint

%matplotlib inline

### Classes and Functions

### Physical and Material Properties

In [2]:
# number of bodies (elements)
n = 12
nGEBF = 12

# Physical Properties
A   =  np.pi*0.01**2
I   =  1.215e-8
L   =  1.2
l   =  L/n

# Material Properties
E   =  0.7e6
rho =  5540

### Initial Conditions

In [3]:
# start the rope from the horizontal 
# Compute initial generalized coordinates
'''q = ['u_1x','u_1y',theta_1,'u_2x','u_2y','theta_2']'''
stateGEBF = np.array([[0,0,0,0,0,0,0,0] 
             for i in range(1,n+1)])
print(stateGEBF)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


### Initilize the bodies and joints of the system (compute inertial properties)

In [4]:
# Create a list of Bodies and Joints
bodiesGEBF = [MB.GEBF_Element(A, E, I, rho, l, state) for i,state in zip(range(nGEBF), stateGEBF)] # (element)
# This is needed to use the standard O-DCA assembly and disassembly operations 
bodies = bodiesGEBF
joints = [MB.Joint(np.array([0, 0, 0, 0, 0]),0) for i in range (n)] # (nodes)

In [6]:
# Helper Function
#-------------------------
#This function provides a buffer between the dca algorithm and the 
#integrator call. 
def dcaHelp(y, t, n, bodies, joints, BC1, BC2):

    # update state depedent quantities  
    initialize(bodies, y, n)
    
    # DCA returns the eddot vector
    qddot = recursiveDCA(n,0,bodies,joints,BC1,BC2,state)
    
    # add the velocities to the state vector and return to the integrator
    ydot = qddot
    ydot[:n] = y[n:]
    return ydot 

### Integration

In [9]:
# scipy.integrate.odeint is the numerical integrator used
#Length of time of the simulation
# Time=np.arange(0,5,.01)
y = odeint(dcaHelp,stateGEBF,0.1,(n,0,bodiesGEBF,joints,2,1))

ValueError: object too deep for desired array

In [ ]:
# Energy Calculation
#--------------------
#The energy of the system is calculated and plotted

energy=MBF.PendEnergy(y,elements)
KE=energy[:,0]
PE=energy[:,1]
TE=energy[:,2]

plt.plot(t,TE-TE[0])
plt.xlabel("Time [s]")
plt.ylabel("energy")
plt.title("System Energy")
plt.show()

plt.plot(t,PE,Time,KE)
plt.xlabel("Time[s]")
plt.ylabel("energy")
plt.title("Kinetic and Potential Energy")
plt.show

In [ ]:
# Solution Plot
#--------------------
plt.plot(Time,yy[:,:n])
plt.xlabel("Time [s]")
plt.ylabel("Generalized Coordinates [Rad]")
plt.title("System Response")

plt.show()

plt.plot(Time,yy[:,n:])
plt.xlabel(("Time[s]"))
plt.ylabel(("Generalized Speeds [Rad/s]"))
plt.title("System Response")

plt.show()

In [3]:
25%2

1

In [9]:
import math
print(math.trunc(40/2))
print(40//2)

20
20
